version: '3.1'

services:

  db:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password --local-infile=ON
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./datadir:/opt/datadir

  adminer:
    image: adminer
    restart: always
    ports:
      - 8283:8080